name: blogPush

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'The message to echo'  # 輸入的描述
        required: true                      # 這個輸入是否必須
        default: 'Hello World!'             # 預設值
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line code
      run: echo "${{ github.event.inputs.message }}"
