name: blogPush

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job to run'
        required: false

jobs:
  publish_blog_file:
    if: ${{ github.event.inputs.job_id == 'publish_blog_file' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Create directory for content
        run: mkdir -p content

      - name: Find and Copy corresponding S3 folder
        run: |
          file_title="xxxx"  # Ensure this is correctly determined or passed as a variable
          aws s3 cp s3://github-action-filepulltest/$file_title ./content/$file_title/ --recursive

      - name: Set git identity
        run: |-
          git config user.name "Uxingouo"
          git config user.email "asd95374118@gmail.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -s -m "Add files to content directory"
          git push -u origin main
