name: blogPush

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job to run'
        required: true
      file_title:
        description: 'Title of the file to fetch from S3'
        required: true

jobs:
  publish_blog_file:
    if: ${{ github.event.inputs.job_id == 'publish_blog_file' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Create directory for content
        run: mkdir -p content

      - name: Find and Copy corresponding S3 folder
        run: |
          file_title="${{ github.event.inputs.file_title }}"
          aws s3 cp s3://github-action-filepulltest/$file_title ./content/$file_title/ --recursive

      - name: Set git identity
        run: |-
          git config user.name "Uxingouo"
          git config user.email "asd95374118@gmail.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -s -m "Add ${{ github.event.inputs.file_title }} to content directory"
          git push -u origin main
  
  delete_blog_folder:
    if: ${{ github.event.inputs.job_id == 'delete_blog_folder' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete directory for content
        run: |
          file_title="${{ github.event.inputs.file_title }}"
          rm -rf content/$file_title
          if [ -d "content/$file_title" ]; then
            echo "Directory deletion failed"
            exit 1
          fi

      - name: Set git identity
        run: |-
          git config user.name "Uxingouo"
          git config user.email "asd95374118@gmail.com"

      - name: Commit and push deletion
        run: |
          git add .
          git commit -s -m "Remove content directory for ${{ github.event.inputs.file_title }}"
          git push -u origin main
